version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-donor_app}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-donor_app}
      - CONFIG_FILE=${CONFIG_FILE:-config.dev}
      - FLASK_ENV=${FLASK_ENV:-development}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-donor_app}
    volumes:
      - ./config:/app/config
      - ./init-db.sh:/app/init-db.sh
    ports:
      - "5001:5000"
    depends_on:
      postgres:
        condition: service_healthy
    command: ["/bin/bash", "/app/init-db.sh", "flask", "run", "--host=0.0.0.0"]

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-donor_app}
      - CONFIG_FILE=${CONFIG_FILE:-config.dev}
      - FLASK_ENV=${FLASK_ENV:-development}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-donor_app}
    volumes:
      - ./config:/app/config
    depends_on:
      postgres:
        condition: service_healthy
    command: ["/bin/sh", "-c", "while true; do echo \"Running donation processing `date`\"; python /app/manage.py process_donations; sleep 60; done"]

  vue-frontend:
    build:
      context: .
      dockerfile: DonorDashUI/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./DonorDashUI/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask-api

volumes:
  postgres_data:
