version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-donor_app}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-donor_app}
      - CONFIG_FILE=${CONFIG_FILE:-config.dev}
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-donor_app}
      - ENVIRONMENT=dev
    volumes:
      - ./config:/app/config
      - ./init-db.sh:/app/init-db.sh
      - .:/app  # Mount entire project directory for hot reloading
    ports:
      - "5001:5000"
    depends_on:
      postgres:
        condition: service_healthy
    command: ["/bin/bash", "/app/init-db.sh", "flask", "run", "--host=0.0.0.0", "--reload"]
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-donor_app}
      - CONFIG_FILE=${CONFIG_FILE:-config.dev}
      - FLASK_ENV=${FLASK_ENV:-development}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-donor_app}
      - ENVIRONMENT=dev
    volumes:
      - ./config:/app/config
      - .:/app  # Mount entire project directory for hot reloading
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    depends_on:
      - flask-api
    command: ["/bin/sh", "-c", "while true; do echo \"Running donation processing `date`\"; cd /app && FLASK_APP=manage.py flask process-donations; sleep 60; done"]
  vue-frontend:
    build:
      context: .
      dockerfile: DonorDashUI/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./DonorDashUI/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask-api
  test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/donor_app_test
      - CONFIG_FILE=config.test
      - FLASK_ENV=testing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=donor_app_test
      # - ENVIRONMENT=test
      - ENVIRONMENT=dev
    volumes:
      - .:/app
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    depends_on:
      - flask-api
    entrypoint: ["/bin/bash", "-c", "export FLASK_APP=manage.py && until PGPASSWORD=password psql -h postgres -U postgres postgres -c '\\q'; do echo 'Waiting for PostgreSQL...'; sleep 1; done && PGPASSWORD=password psql -h postgres -U postgres postgres -c 'CREATE DATABASE donor_app_test WITH OWNER postgres;' || true && flask db upgrade && python -m pytest donordash/tests"]
    command: []

volumes:
  postgres_data:
