services:
  - type: web
    name: donordash
    env: python
    buildCommand: pip install -r pip.txt
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: ENVIRONMENT
        value: production
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: donordash-db
          property: connectionString

databases:
  - name: donordash-db
    databaseName: donordash
    user: donordash
