"""fix4

Revision ID: 0e6796065ff8
Revises: c4cfe355a7d6
Create Date: 2019-07-24 23:53:07.695064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e6796065ff8'
down_revision = 'c4cfe355a7d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donation', sa.Column('anonymous', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donation', 'anonymous')
    # ### end Alembic commands ###
