name: Donor Dashboard CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker images
      run: docker compose build

    - name: Run linting checks
      run: |
        docker compose run --rm flask-api black --check /app
        docker compose run --rm flask-api isort --check /app
        docker compose run --rm flask-api flake8 /app

    - name: Run tests
      run: |
        docker compose run --rm test

    - name: Cleanup
      run: docker compose down
